name: cma-aks
version: 0.1.0
description: The Cluster Manager API AKS Helper
keywords:
- hybridstack
- api
home: https://github.com/samsung-cnct/cma-aks
sources:
- https://github.com/samsung-cnct/cma-aks
maintainers:
- name: Michael Venezia
  email: mvenezia@gmail.com
icon: https://github.com/samsung-cnct/solas/docs/images/samsung-logo.svg
engine: gotpl
